import Head from "next/head";
import Image from "next/image";
import Hero from "../components/Hero/Hero";
import Link from "next/link";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Hero heading1={"Hello TUPC!"} />
        <div>
          <Link href="/tupc">TUPC Page</Link>
        </div>
      </main>
    </div>
  );
}
